{"name": "test_ct53", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "def test_ct53():\n        webdriver.get(url)\n        inscricao_externo.caminho(True)\n>       inscricao_externo.ct53_inscricao_externo(\n            cpf         = '24643211091',\n            nome        = 'Participante Externo Teste 2',\n            email       = 'pexterno2@teste.com',\n            telefone    = '43663346970',\n            celular     = '51405531810'\n        )\n\ntests\\test_inscricao_externo.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.page_inscricao_externo.inscricaoExterno object at 0x0000022AA5A1F910>, cpf = '24643211091', nome = 'Participante Externo Teste 2', email = 'pexterno2@teste.com', telefone = '43663346970', celular = '51405531810'\n\n    def ct53_inscricao_externo(self, cpf, nome, email, telefone, celular):\n        txt = \"Inscrição solicitada!\"\n        try:\n            self.find_element(self.ultima_pagina).click()\n            sleep(1)\n            self.find_element(self.atividade_ct51).click()\n            sleep(1)\n            self.find_element(self.cpf).send_keys(cpf)\n            self.find_element(self.nome).send_keys(nome)\n            self.find_element(self.email).send_keys(email)\n            self.find_element(self.confirmar).click()\n            sleep(1)\n            self.find_element(self.telefone).send_keys(telefone)\n            self.find_element(self.celular).send_keys(celular)\n            self.find_element(self.concluir).click()\n            msg = self.espera_mensagem()\n            if msg is True:\n                if txt in self.find_element(self.alert_texto).text:\n                    print(\"\\n [!] CT_53 sem erros: \" + self.find_element(self.alert_texto).text)\n>                   assert False\nE                   AssertionError\n\npages\\page_inscricao_externo.py:119: AssertionError"}, "start": 1606194990221, "stop": 1606194997734, "uuid": "fd78e712-97b6-435c-a8a8-d18474c52356", "historyId": "4c288e6aca1939adc22f9898ab9b7f61", "testCaseId": "0dc6461b314222d7694a87c63d32e5a2", "fullName": "tests.test_inscricao_externo#test_ct53", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_inscricao_externo"}, {"name": "host", "value": "DESKTOP-OFT3SDL"}, {"name": "thread", "value": "12564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_inscricao_externo"}]}